version: '3.7'

services:
  app:
    ports:
      - "${APP_PORT:-8400}:8400"
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/src
      - /src/vendor
      - /src/tmp
    env_file:
      - app.env
    restart: unless-stopped
    extra_hosts:
      - "internal.host:host-gateway"


